
export const ACTION = {
  SHOW_FORM: "SHOW_FORM",
  
  GET_CONTACT_API: "GET_CONTACT_API",
  PENDING: "PENDING",
  NEW_CONTACT: "NEW_CONTACT",
  DELETE_CONTACT: "DELETE_CONTACT",
  SHOW_CONTACTS_DELETED: "SHOW_CONTACTS_DELETED",
  
  ADD_FAVORITES: "ADD_FAVORITES",
  REMOVE_FAVORITES: "REMOVE_FAVORITES",
}